#! /bin/sh

sxhkd &
bspc monitor -d 1 2 3 4 5 6 7

#Border gaps settings
bspc config border_width         4
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Colors settings
bspc config focused_border_color "#b7d3f2"
bspc config normal_border_color "#eff3f6"
bspc config active_border_color "#eff3f6"
bspc config urgent_border_color "#ebcb8b"

#Workspaces settings
bspc rule -a 'Firefox' desktop='^1'
bspc rule -a 'Pcmanfm' desktop='^3'
bspc rule -a 'mpv' desktop='^4'
bspc rule -a 'Inkscape' desktop='^5'
bspc rule -a 'Steam' desktop='^7'
bspc rule -a 'ppsspp-sdl' desktop='^7'
bspc rule -a 'PCSX2' desktop='^7'

#Wallpaper settings
feh --bg-fill '/home/lyes/Images/Wallpaper/wallpaper.jpg'
#mpv --wid=0 --loop-file=inf /home/lyes/Images/Wallpaper/wallpaper.mp4
